ALTER TABLE students 
ADD COLUMN year_of_study VARCHAR(10) NOT NULL,
ADD COLUMN major VARCHAR(255) NOT NULL,
ADD COLUMN id_card_front VARCHAR(255) DEFAULT NULL,
ADD COLUMN id_card_back VARCHAR(255) DEFAULT NULL,
ADD COLUMN payment_receipt VARCHAR(255) DEFAULT NULL;
